# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 13 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "guzzle_sphinx_theme" %}
{% set version = "0.7.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  noarch: python
  number: 0

requirements:
  build:
    - python>=3.6
  host:
    - python>=3.6
    - sphinx
  run:
    - python>=3.6
    - sphinx
  
test:
  # Python imports
  imports:
    - guzzle_sphinx_theme

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  license: MIT
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
